version: '2'
services:
    nginx:
        image: "nginx"
        ports:
          - "80:80"
        volumes:
          - ./etc/nginx:/etc/nginx
          - ./app/web:/app/web
        links:
          - php7-fpm:php-fpm
        depends_on:
          - php7-fpm
    php7-fpm:
        image: "zterry95/docker-php7-memcached"
        volumes:
          - ./app/web:/app/web
        depends_on:
          - mysql
          - memcached
        links:
          - mysql:mysql
          - memcached:memcached
    mysql:
        image: mysql:5.7
        ports:
          - "3306:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./etc/mysql:/etc/mysql/conf.d
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: Abcd@1234~
    memcached:
        image: memcached
        ports:
          - "11211:11211"
        mem_limit: 256M 
