version: '2'
services:
  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx:/etc/nginx
      - ./app/web:/app/web
    links:
      - php7-fpm:php-fpm
    depends_on:
      - php7-fpm
  php7-fpm:
    image: "zterry95/docker-php7:7.1-memcached"
    volumes:
      - ./app/web:/app/web
      - ./etc/php:/usr/local/etc/php
      - ./etc/php-fpm:/usr/local/etc
    depends_on:
      - mysql
      - memcached
    links:
      - mysql:mysql
      - memcached:memcached
  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    #mem_limit: 2500M
    #cpuset: 1,3
  memcached:
    image: memcached
    mem_limit: 128M
    command: memcached -m 128M
